BootLeg/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BootLeg.Models;

namespace BootLeg.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            BootLegEntities bootLegEntities = new BootLegEntities();
            OrderViewModel orderViewModel = new OrderViewModel();
            orderViewModel.order = bootLegEntities.Orders.ToList();
            return View(orderViewModel);
        }

        [HttpGet]
        public ActionResult AddOrder()
        {
            Order order = new Order();
            return View(order);
        }
        [HttpPost]
        public ActionResult AddOrder(Order order)
        {
            BootLegEntities bootLegEntities = new BootLegEntities();
            bootLegEntities.Orders.Add(order);
            bootLegEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditOrder(int Id)
        {
            BootLegEntities bootLegEntities = new BootLegEntities();
            Order order = bootLegEntities.Orders.Single(x => x.Id == Id);
            return View(order);
            
        }
       [HttpPost]
        public ActionResult EditOrder(Order order)
        {
            BootLegEntities bootLegEntities = new BootLegEntities();
            Order order1 = bootLegEntities.Orders.SingleOrDefault(x => x.Id == order.Id);

            order1.Id = order.Id;
            order1.OrderTypeId = order.OrderTypeId;
            bootLegEntities.SaveChanges();
            return RedirectToAction("Index");

        }
      
    }
}

BootLeg/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        ul li:hover .erji_ul {display:block;}
        .dropdown {
            position:relative;
            display:inline-block;
        }
        .dropdown-content {
            display:none;
            position:absolute;
            background-color:#f9f9f9;
            min-width:160px;
            box-shadow:0px 32px 128px 0px rgba(0,0,0,0.2);
            padding:12px 16px;
        }
        .dropdown:hover .dropdown-content {
            display: block;
        }
        .phg {
            color:white;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("SupplierName", "SupplierName", "Supplier")</li>
                    <li>@Html.ActionLink("OrderManagement", "Index", "Order")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                                data-toggle="dropdowm">
                        Reservation<span class="caret"></span></a>
                        <ul class="dropdown-content">
                            <li class="erji">@Html.ActionLink("Table Management", "TableView", "Reservation")</li>
                            <li class="erji">@Html.ActionLink("Reservation Management", "ReservationView", "Reservation")</li>
                            <li class="erji">@Html.ActionLink("Reservation Order Management", "ReservationOrderView", "Reservation")</li>
                        </ul>
                        
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="modal fade" id="craigs-model" tabindex="-1" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">Edit Student Profile</h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" id="edit-student-form"></form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="save-changes-btn btn btn-primary">Save changes</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div><!-- /.container -->
        
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    

    
        
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    
</body>
</html>